[[hasura.jwtSecrets]]
type = 'RS256'
key = '{{ secrets.NHOST_JWT_PUBLIC_KEY }}'



[postgres.resources.storage]
capacity = 1

[observability.grafana]
adminPassword = '{{ secrets.GRAFANA_ADMIN_PASSWORD }}'
