[[hasura.jwtSecrets]]
type = "RS256"
key = "{{ secrets.NHOST_JWT_PUBLIC_KEY }}"
signingKey = "{{ secrets.NHOST_JWT_PRIVATE_KEY }}"
kid = "{{ secrets.NHOST_JWT_KID }}"

[[auth.session.accessToken.customClaims]]
key = 'user-as'
value = 'appUser.id'